name: Docker Image Push

on:
  push:
    branches: [main]
  merge_group:
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: docker.io
  IMAGE_NAME: trueberryless/chat

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    name: Build and push docker image to docker hub
    steps:
      - id: build-and-push-to-docker-hub
        uses: trueberryless-org/version-build-push-docker-action@main
        with:
          IMAGE_NAME: trueberryless/chat
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: echo-versions
        run: |
          echo ${{ steps.build-and-push-to-docker-hub.outputs.version }}
          echo ${{ steps.build-and-push-to-docker-hub.outputs.version-major }}
          echo ${{ steps.build-and-push-to-docker-hub.outputs.version-minor }}
          echo ${{ steps.build-and-push-to-docker-hub.outputs.version-patch }}
